#!/bin/bash

domain=$(sudo yunohost app setting letschat domain)

# Stop services
sudo service letschat stop

# Remove sources
sudo rm -rf /var/www/letschat

# Remove configuration files
sudo rm -f /etc/nginx/conf.d/$domain.d/letschat.conf
sudo rm /etc/init.d/letschat 
