#!/bin/bash -ex

# Retrieve arguments
domain=$(sudo yunohost app setting letschat domain)
is_public=$(sudo yunohost app setting letschat is_public)
path=""

# Install sources
root_path=$(pwd)/..
sources_path=$root_path/sources
final_path=/var/www/letschat
cd $root_path
git submodule init
git submodule update
sudo mkdir -p $final_path
sudo cp -rf $sources_path/lets-chat/* $final_path
sudo cp $root_path/conf/settings.yml $final_path/settings.yml

# Install app dependencies
cd $final_path
sudo npm cache clear
sudo npm install
sudo npm install $sources_path/lets-chat-ldap
cd -

# Set permissions to app directory
sudo chown -R www-data: $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sudo cp $root_path/conf/nginx.conf-nosub /etc/nginx/conf.d/$domain.d/letschat.conf

# Copy init.d script
sudo cp $root_path/conf/letschat /etc/init.d/
sudo chmod +x /etc/init.d/letschat

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
if [ "$is_public" = "Yes" ];
then
    sudo yunohost app setting letschat unprotected_uris -v "/"
fi
sudo yunohost app ssowatconf

# Start app
sudo service letschat restart
